# Generated by Django 2.2 on 2020-08-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('productClassId', models.AutoField(primary_key=True, serialize=False, verbose_name='商品类别编号')),
                ('productClassName', models.CharField(default='', max_length=20, verbose_name='商品类别名称')),
            ],
            options={
                'verbose_name': '商品类别信息',
                'verbose_name_plural': '商品类别信息',
                'db_table': 't_ProductClass',
            },
        ),
    ]
