# Generated by Django 2.2 on 2020-08-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplyer',
            fields=[
                ('supplyerId', models.AutoField(primary_key=True, serialize=False, verbose_name='供应商编号')),
                ('supplyerName', models.CharField(default='', max_length=20, verbose_name='供应商名称')),
                ('telephone', models.CharField(default='', max_length=20, verbose_name='供应商电话')),
                ('personName', models.CharField(default='', max_length=20, verbose_name='联系人')),
                ('address', models.CharField(default='', max_length=20, verbose_name='供应商地址')),
            ],
            options={
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
                'db_table': 't_Supplyer',
            },
        ),
    ]
