# Generated by Django 2.2 on 2020-08-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CustomerInfo', '0001_initial'),
        ('ProductInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellInfo',
            fields=[
                ('sellId', models.AutoField(primary_key=True, serialize=False, verbose_name='销售编号')),
                ('sellDate', models.CharField(default='', max_length=20, verbose_name='销售日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售价格')),
                ('count', models.IntegerField(default=0, verbose_name='销售数量')),
                ('personName', models.CharField(default='', max_length=20, verbose_name='销售负责人')),
                ('customerObj', models.ForeignKey(db_column='customerObj', on_delete=django.db.models.deletion.PROTECT, to='CustomerInfo.CustomerInfo', verbose_name='销售客户')),
                ('productObj', models.ForeignKey(db_column='productObj', on_delete=django.db.models.deletion.PROTECT, to='ProductInfo.ProductInfo', verbose_name='销售产品')),
            ],
            options={
                'verbose_name': '产品销售信息',
                'verbose_name_plural': '产品销售信息',
                'db_table': 't_SellInfo',
            },
        ),
    ]
