# Generated by Django 2.2 on 2020-08-21 08:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProductClass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('productNo', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='产品编号')),
                ('productName', models.CharField(default='', max_length=20, verbose_name='产品名称')),
                ('productPhoto', models.ImageField(max_length='100', upload_to='img', verbose_name='产品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='产品单价')),
                ('leftCount', models.IntegerField(default=0, verbose_name='产品库存')),
                ('madeDate', models.CharField(default='', max_length=20, verbose_name='生产日期')),
                ('productDesc', tinymce.models.HTMLField(max_length=8000, verbose_name='产品描述')),
                ('productClass', models.ForeignKey(db_column='productClass', on_delete=django.db.models.deletion.PROTECT, to='ProductClass.ProductClass', verbose_name='产品类别')),
            ],
            options={
                'verbose_name': '产品信息信息',
                'verbose_name_plural': '产品信息信息',
                'db_table': 't_ProductInfo',
            },
        ),
    ]
